version: '3.9'


services:

 php:
  container_name: php_83
  ports:
    - 8000:80
  volumes:
    - .:/var/www/html
  build:
    context: .
    dockerfile: Dockerfile

 db:
    image: mysql:latest
    container_name: mysql-arc
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: cHampiondEv85
      MYSQL_DATABASE: arcadia
      MYSQL_USER: jeAn-phI
      MYSQL_PASSWORD: J25061984c%#
    ports:
      - 3307:3306
   